title: State of the Map Japan 2024
description: 世界を自由な地図にしよう
lang: ja
timezone: Asia/Tokyo
destination: "2024"

event:
  title: State of the Map Japan 2024
  date: 2024年2月15日
  dayofweek: 土曜日
  time: 13:00 - 18:00
  venue: EZOHUB SAPPORO BOOK LAUNGE
  zip: 060-0908
  address: 北海道札幌市東区北8条東4丁目1-20 2階
  map: https://osm.org/go/7XGQI~Vn?m=
  lat: 43.07185
  lon: 141.35982
  fee: 無料
  theme: Re:mapping
  message: OpenStreetMapは「自由な地図をみんなの手に」をスローガンに作成した地図データの集合体です。わたしたちは、この活動をさらに発展させるためにカンファレンスを企画しました。
  target: OpenStreetMap編集者、企業、技術者、研究者、行政関係者、シビックテックなどのコミュニティが集まり、各地・各領域の発表や交流を行います。
  host:
    - name: State of the Map Japan 2024 実行委員会
      url: https://stateofthemap.jp/2024/
  chairman: 
  cohost:
    - name: 一般社団法人 OpenStreetMap Foundation Japan
      url: https://www.osmf.jp/
  support:

social:
  - title: OpenStreetMap Foundation Japan
    icon: twitter
    url: https://twitter.com/osmfj
  - title: OpenStreetMap Foundation Japan
    icon: facebook
    url: https://www.facebook.com/osmfj
  - title: youtube
    icon: youtube
    url: https://www.youtube.com/channel/UCKS6DjwrVC1gEx6PO0nX3TQ
  - title: github
    icon: github
    url: https://github.com/osmfj
  - title: wiki
    icon: pencil-square
    url: https://wiki.openstreetmap.org/wiki/JA:Main_Page
